name: qr_attendance_app
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Modern, Dart 3-compatible packages
  barcode_scan2: ^4.2.0
  qr_flutter: ^4.0.0
  path_provider: ^2.1.2
  http: ^1.1.0
  fluttertoast: ^8.2.4
  intl: ^0.18.1
  flutter_svg: ^2.0.10+1
  percent_indicator: ^4.2.3
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/home.svg
    - assets/home.jpg
    - assets/home.png
    - assets/student.svg
    - assets/stud_log.svg
    - assets/admin_login.svg
    - assets/classbuilder.svg
    - assets/studentqr.svg
    - assets/phone.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Poppins-Medium.ttf
